kind = "DojoModel"
class_hash = "0x55a1561a2665c2eae918707594310ccf85ae9853dcfd990a5d3fa4696ab7163"
original_class_hash = "0x55a1561a2665c2eae918707594310ccf85ae9853dcfd990a5d3fa4696ab7163"
abi = "manifests/dev/abis/base/models/dojo_starter_models_user_user.json"
name = "dojo_starter::models::user::user"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "state"
type = "UserState"
key = false

[[members]]
name = "score"
type = "u32"
key = false
