kind = "DojoModel"
class_hash = "0x116bd2d7a22ea4136d73476bab62a1add26f1ef13363608bea06f7daaf75359"
original_class_hash = "0x116bd2d7a22ea4136d73476bab62a1add26f1ef13363608bea06f7daaf75359"
abi = "manifests/dev/abis/base/models/dojo_starter_models_role_role.json"
name = "dojo_starter::models::role::role"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "seed"
type = "u64"
key = false

[[members]]
name = "cur_stage"
type = "u32"
key = false

[[members]]
name = "stage_category"
type = "StageCategory"
key = false

[[members]]
name = "category"
type = "RoleCategory"
key = false

[[members]]
name = "gold"
type = "u32"
key = false

[[members]]
name = "card_slot"
type = "u256"
key = false

[[members]]
name = "blessing_slot"
type = "u256"
key = false

[[members]]
name = "property"
type = "Property"
key = false
