kind = "DojoModel"
class_hash = "0x457d6bf48e7199891c8f11cbbc321ff1a2e8651650fefa7256b023298a36e1a"
original_class_hash = "0x457d6bf48e7199891c8f11cbbc321ff1a2e8651650fefa7256b023298a36e1a"
abi = "manifests/dev/abis/base/models/dojo_starter_models_card_card.json"
name = "dojo_starter::models::card::card"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "uid"
type = "u32"
key = true

[[members]]
name = "id"
type = "CardID"
key = false

[[members]]
name = "level"
type = "u32"
key = false
