// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:48:48 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `dojo_starter::models::card::CardID` enum
public enum CardID {
    None,
    Attack,
    Smash,
    InfiniteStrike,
    BladeDance,
    Bloodthirst,
    Defence,
    Fever,
    Shout,
    ShiledWall,
    Avatar,
    DefensiveStance,
    BerserkerStance,
    Bloodbath,
    Bastion,
    ShowofPower,
}


// Model definition for `dojo_starter::models::card::Card` model
public class Card : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("uid")]
    public uint uid;

    [ModelField("id")]
    public CardID id;

    [ModelField("level")]
    public uint level;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        