// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:48:48 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `dojo_starter::models::user::UserState` enum
public enum UserState {
    None,
    Free,
    StageBegin,
    StageEnd,
}


// Model definition for `dojo_starter::models::user::User` model
public class User : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("state")]
    public UserState state;

    [ModelField("score")]
    public uint score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        