kind = "DojoContract"
class_hash = "0x72c65c5ca0f00edf30c6774e3ceada203f3e1e1840142850a805608aa766e3"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
