[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"
transaction_hash = "0x7f1456c94b5cc20a043c7acb7e183a31b57b6de82699b062498189f8aae9d0b"
block_number = 85
seed = "dojo_starter"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x7ec42d76c6d876b8f219c20b6a152fe35fe2afc62c471b29ba689c2f6a075b3"
class_hash = "0x4801fdb68ae669fef76fb443cb23ba4e67422e894aafae0eb07f78169aef2e5"
original_class_hash = "0x4801fdb68ae669fef76fb443cb23ba4e67422e894aafae0eb07f78169aef2e5"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x457d6bf48e7199891c8f11cbbc321ff1a2e8651650fefa7256b023298a36e1a"
original_class_hash = "0x457d6bf48e7199891c8f11cbbc321ff1a2e8651650fefa7256b023298a36e1a"
abi = "abis/deployments/models/dojo_starter_models_card_card.json"
name = "dojo_starter::models::card::card"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "uid"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "CardID"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x116bd2d7a22ea4136d73476bab62a1add26f1ef13363608bea06f7daaf75359"
original_class_hash = "0x116bd2d7a22ea4136d73476bab62a1add26f1ef13363608bea06f7daaf75359"
abi = "abis/deployments/models/dojo_starter_models_role_role.json"
name = "dojo_starter::models::role::role"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "seed"
type = "u64"
key = false

[[models.members]]
name = "cur_stage"
type = "u32"
key = false

[[models.members]]
name = "stage_category"
type = "StageCategory"
key = false

[[models.members]]
name = "category"
type = "RoleCategory"
key = false

[[models.members]]
name = "gold"
type = "u32"
key = false

[[models.members]]
name = "card_slot"
type = "u256"
key = false

[[models.members]]
name = "blessing_slot"
type = "u256"
key = false

[[models.members]]
name = "property"
type = "Property"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x55a1561a2665c2eae918707594310ccf85ae9853dcfd990a5d3fa4696ab7163"
original_class_hash = "0x55a1561a2665c2eae918707594310ccf85ae9853dcfd990a5d3fa4696ab7163"
abi = "abis/deployments/models/dojo_starter_models_user_user.json"
name = "dojo_starter::models::user::user"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "state"
type = "UserState"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false
